created account page
wolffles/StayFreshers pull request #15
Opened 2017-11-11 21:19 UTC by wolffles

description: this branch was to create a basic interface to view account information such as test_sets.
test coverage: 98.33%

resolving card #11

2017-11-11 23:57 UTC, brittanyjspringer requested changes

2017-11-11 23:57 UTC, wonderwoman13 commented on spec/controllers/user/user_controller_spec.rb
> +require 'rails_helper'
@wolffles This says Welcome and it should also have some tests.

2017-11-11 23:57 UTC, wonderwoman13 commented on coverage/.resultset.json
>  {
@wolffles please add your /coverage/* folder to your .gitignore. I'd prefer not to see these files.

2017-11-12 16:57 UTC, wolffles commented
i added a test for the controller index action but the redirect helper function I don't know how to test for that. it just adds a parameter to devises sessions controller, so can I just leave that?

2017-11-12 19:02 UTC, wonderwoman13 commented
Yes, you can just leave the sessions method since Devise covers it.

2017-11-12 19:02 UTC, merged